export const REGIONS = [
  {label: 'Africa', value: 'Africa'},
  {label: 'Americas', value: 'Americas'},
  {label: 'Asia', value: 'Asia'},
  {label: 'Europe', value: 'Europe'},
  {label: 'Oceania', value: 'Oceania'},
  {label: 'Antarctic', value: 'Antarctic'},
];

export const alphaCca3Map = {
  AFG: {cca2: 'AF', Country: 'Afghanistan'},
  ALB: {cca2: 'AL', Country: 'Albania'},
  DZA: {cca2: 'DZ', Country: 'Algeria'},
  ASM: {cca2: 'AS', Country: 'American Samoa'},
  AND: {cca2: 'AD', Country: 'Andorra'},
  AGO: {cca2: 'AO', Country: 'Angola'},
  AIA: {cca2: 'AI', Country: 'Anguilla'},
  ATA: {cca2: 'AQ', Country: 'Antarctica'},
  ATG: {cca2: 'AG', Country: 'Antigua and Barbuda'},
  ARG: {cca2: 'AR', Country: 'Argentina'},
  ARM: {cca2: 'AM', Country: 'Armenia'},
  ABW: {cca2: 'AW', Country: 'Aruba'},
  AUS: {cca2: 'AU', Country: 'Australia'},
  AUT: {cca2: 'AT', Country: 'Austria'},
  AZE: {cca2: 'AZ', Country: 'Azerbaijan'},
  BHS: {cca2: 'BS', Country: 'Bahamas'},
  BHR: {cca2: 'BH', Country: 'Bahrain'},
  BGD: {cca2: 'BD', Country: 'Bangladesh'},
  BRB: {cca2: 'BB', Country: 'Barbados'},
  BLR: {cca2: 'BY', Country: 'Belarus'},
  BEL: {cca2: 'BE', Country: 'Belgium'},
  BLZ: {cca2: 'BZ', Country: 'Belize'},
  BEN: {cca2: 'BJ', Country: 'Benin'},
  BMU: {cca2: 'BM', Country: 'Bermuda'},
  BTN: {cca2: 'BT', Country: 'Bhutan'},
  BOL: {cca2: 'BO', Country: 'Bolivia'},
  BIH: {cca2: 'BA', Country: 'Bosnia and Herzegovina'},
  BWA: {cca2: 'BW', Country: 'Botswana'},
  BVT: {cca2: 'BV', Country: 'Bouvet Island'},
  BRA: {cca2: 'BR', Country: 'Brazil'},
  IOT: {cca2: 'IO', Country: 'British Indian Ocean Territory'},
  BRN: {cca2: 'BN', Country: 'Brunei'},
  BGR: {cca2: 'BG', Country: 'Bulgaria'},
  BFA: {cca2: 'BF', Country: 'Burkina Faso'},
  BDI: {cca2: 'BI', Country: 'Burundi'},
  KHM: {cca2: 'KH', Country: 'Cambodia'},
  CMR: {cca2: 'CM', Country: 'Cameroon'},
  CAN: {cca2: 'CA', Country: 'Canada'},
  CPV: {cca2: 'CV', Country: 'Cape Verde'},
  CYM: {cca2: 'KY', Country: 'Cayman Islands'},
  CAF: {cca2: 'CF', Country: 'Central African Republic'},
  TCD: {cca2: 'TD', Country: 'Chad'},
  CHL: {cca2: 'CL', Country: 'Chile'},
  CHN: {cca2: 'CN', Country: 'China'},
  CXR: {cca2: 'CX', Country: 'Christmas Island'},
  CCK: {cca2: 'CC', Country: 'Cocos (Keeling) Islands'},
  COL: {cca2: 'CO', Country: 'Colombia'},
  COM: {cca2: 'KM', Country: 'Comoros'},
  COG: {cca2: 'CG', Country: 'Congo'},
  COD: {cca2: 'CD', Country: 'Congo, the Democratic Republic of the'},
  COK: {cca2: 'CK', Country: 'Cook Islands'},
  CRI: {cca2: 'CR', Country: 'Costa Rica'},
  CIV: {cca2: 'CI', Country: 'Ivory Coast'},
  HRV: {cca2: 'HR', Country: 'Croatia'},
  CUB: {cca2: 'CU', Country: 'Cuba'},
  CYP: {cca2: 'CY', Country: 'Cyprus'},
  CZE: {cca2: 'CZ', Country: 'Czech Republic'},
  DNK: {cca2: 'DK', Country: 'Denmark'},
  DJI: {cca2: 'DJ', Country: 'Djibouti'},
  DMA: {cca2: 'DM', Country: 'Dominica'},
  DOM: {cca2: 'DO', Country: 'Dominican Republic'},
  ECU: {cca2: 'EC', Country: 'Ecuador'},
  EGY: {cca2: 'EG', Country: 'Egypt'},
  SLV: {cca2: 'SV', Country: 'El Salvador'},
  GNQ: {cca2: 'GQ', Country: 'Equatorial Guinea'},
  ERI: {cca2: 'ER', Country: 'Eritrea'},
  EST: {cca2: 'EE', Country: 'Estonia'},
  ETH: {cca2: 'ET', Country: 'Ethiopia'},
  FLK: {cca2: 'FK', Country: 'Falkland Islands (Malvinas)'},
  FRO: {cca2: 'FO', Country: 'Faroe Islands'},
  FJI: {cca2: 'FJ', Country: 'Fiji'},
  FIN: {cca2: 'FI', Country: 'Finland'},
  FRA: {cca2: 'FR', Country: 'France'},
  GUF: {cca2: 'GF', Country: 'French Guiana'},
  PYF: {cca2: 'PF', Country: 'French Polynesia'},
  ATF: {cca2: 'TF', Country: 'French Southern Territories'},
  GAB: {cca2: 'GA', Country: 'Gabon'},
  GMB: {cca2: 'GM', Country: 'Gambia'},
  GEO: {cca2: 'GE', Country: 'Georgia'},
  DEU: {cca2: 'DE', Country: 'Germany'},
  GHA: {cca2: 'GH', Country: 'Ghana'},
  GIB: {cca2: 'GI', Country: 'Gibraltar'},
  GRC: {cca2: 'GR', Country: 'Greece'},
  GRL: {cca2: 'GL', Country: 'Greenland'},
  GRD: {cca2: 'GD', Country: 'Grenada'},
  GLP: {cca2: 'GP', Country: 'Guadeloupe'},
  GUM: {cca2: 'GU', Country: 'Guam'},
  GTM: {cca2: 'GT', Country: 'Guatemala'},
  GGY: {cca2: 'GG', Country: 'Guernsey'},
  GIN: {cca2: 'GN', Country: 'Guinea'},
  GNB: {cca2: 'GW', Country: 'Guinea-Bissau'},
  GUY: {cca2: 'GY', Country: 'Guyana'},
  HTI: {cca2: 'HT', Country: 'Haiti'},
  HMD: {cca2: 'HM', Country: 'Heard Island and McDonald Islands'},
  VAT: {cca2: 'VA', Country: 'Holy See (Vatican City State)'},
  HND: {cca2: 'HN', Country: 'Honduras'},
  HKG: {cca2: 'HK', Country: 'Hong Kong'},
  HUN: {cca2: 'HU', Country: 'Hungary'},
  ISL: {cca2: 'IS', Country: 'Iceland'},
  IND: {cca2: 'IN', Country: 'India'},
  IDN: {cca2: 'ID', Country: 'Indonesia'},
  IRN: {cca2: 'IR', Country: 'Iran, Islamic Republic of'},
  IRQ: {cca2: 'IQ', Country: 'Iraq'},
  IRL: {cca2: 'IE', Country: 'Ireland'},
  IMN: {cca2: 'IM', Country: 'Isle of Man'},
  ISR: {cca2: 'IL', Country: 'Israel'},
  ITA: {cca2: 'IT', Country: 'Italy'},
  JAM: {cca2: 'JM', Country: 'Jamaica'},
  JPN: {cca2: 'JP', Country: 'Japan'},
  JEY: {cca2: 'JE', Country: 'Jersey'},
  JOR: {cca2: 'JO', Country: 'Jordan'},
  KAZ: {cca2: 'KZ', Country: 'Kazakhstan'},
  KEN: {cca2: 'KE', Country: 'Kenya'},
  KIR: {cca2: 'KI', Country: 'Kiribati'},
  PRK: {cca2: 'KP', Country: "Korea, Democratic People's Republic of"},
  KOR: {cca2: 'KR', Country: 'South Korea'},
  KWT: {cca2: 'KW', Country: 'Kuwait'},
  KGZ: {cca2: 'KG', Country: 'Kyrgyzstan'},
  LAO: {cca2: 'LA', Country: "Lao People's Democratic Republic"},
  LVA: {cca2: 'LV', Country: 'Latvia'},
  LBN: {cca2: 'LB', Country: 'Lebanon'},
  LSO: {cca2: 'LS', Country: 'Lesotho'},
  LBR: {cca2: 'LR', Country: 'Liberia'},
  LBY: {cca2: 'LY', Country: 'Libya'},
  LIE: {cca2: 'LI', Country: 'Liechtenstein'},
  LTU: {cca2: 'LT', Country: 'Lithuania'},
  LUX: {cca2: 'LU', Country: 'Luxembourg'},
  MAC: {cca2: 'MO', Country: 'Macao'},
  MKD: {cca2: 'MK', Country: 'Macedonia, the former Yugoslav Republic of'},
  MDG: {cca2: 'MG', Country: 'Madagascar'},
  MWI: {cca2: 'MW', Country: 'Malawi'},
  MYS: {cca2: 'MY', Country: 'Malaysia'},
  MDV: {cca2: 'MV', Country: 'Maldives'},
  MLI: {cca2: 'ML', Country: 'Mali'},
  MLT: {cca2: 'MT', Country: 'Malta'},
  MHL: {cca2: 'MH', Country: 'Marshall Islands'},
  MTQ: {cca2: 'MQ', Country: 'Martinique'},
  MRT: {cca2: 'MR', Country: 'Mauritania'},
  MUS: {cca2: 'MU', Country: 'Mauritius'},
  MYT: {cca2: 'YT', Country: 'Mayotte'},
  MEX: {cca2: 'MX', Country: 'Mexico'},
  FSM: {cca2: 'FM', Country: 'Micronesia, Federated States of'},
  MDA: {cca2: 'MD', Country: 'Moldova, Republic of'},
  MCO: {cca2: 'MC', Country: 'Monaco'},
  MNG: {cca2: 'MN', Country: 'Mongolia'},
  MNE: {cca2: 'ME', Country: 'Montenegro'},
  MSR: {cca2: 'MS', Country: 'Montserrat'},
  MAR: {cca2: 'MA', Country: 'Morocco'},
  MOZ: {cca2: 'MZ', Country: 'Mozambique'},
  MMR: {cca2: 'MM', Country: 'Myanmar'},
  NAM: {cca2: 'NA', Country: 'Namibia'},
  NRU: {cca2: 'NR', Country: 'Nauru'},
  NPL: {cca2: 'NP', Country: 'Nepal'},
  NLD: {cca2: 'NL', Country: 'Netherlands'},
  ANT: {cca2: 'AN', Country: 'Netherlands Antilles'},
  NCL: {cca2: 'NC', Country: 'New Caledonia'},
  NZL: {cca2: 'NZ', Country: 'New Zealand'},
  NIC: {cca2: 'NI', Country: 'Nicaragua'},
  NER: {cca2: 'NE', Country: 'Niger'},
  NGA: {cca2: 'NG', Country: 'Nigeria'},
  NIU: {cca2: 'NU', Country: 'Niue'},
  NFK: {cca2: 'NF', Country: 'Norfolk Island'},
  MNP: {cca2: 'MP', Country: 'Northern Mariana Islands'},
  NOR: {cca2: 'NO', Country: 'Norway'},
  OMN: {cca2: 'OM', Country: 'Oman'},
  PAK: {cca2: 'PK', Country: 'Pakistan'},
  PLW: {cca2: 'PW', Country: 'Palau'},
  PSE: {cca2: 'PS', Country: 'Palestinian Territory, Occupied'},
  PAN: {cca2: 'PA', Country: 'Panama'},
  PNG: {cca2: 'PG', Country: 'Papua New Guinea'},
  PRY: {cca2: 'PY', Country: 'Paraguay'},
  PER: {cca2: 'PE', Country: 'Peru'},
  PHL: {cca2: 'PH', Country: 'Philippines'},
  PCN: {cca2: 'PN', Country: 'Pitcairn'},
  POL: {cca2: 'PL', Country: 'Poland'},
  PRT: {cca2: 'PT', Country: 'Portugal'},
  PRI: {cca2: 'PR', Country: 'Puerto Rico'},
  QAT: {cca2: 'QA', Country: 'Qatar'},
  REU: {cca2: 'RE', Country: 'Réunion'},
  ROU: {cca2: 'RO', Country: 'Romania'},
  RUS: {cca2: 'RU', Country: 'Russia'},
  RWA: {cca2: 'RW', Country: 'Rwanda'},
  SHN: {cca2: 'SH', Country: 'Saint Helena, Ascension and Tristan da Cunha'},
  KNA: {cca2: 'KN', Country: 'Saint Kitts and Nevis'},
  LCA: {cca2: 'LC', Country: 'Saint Lucia'},
  SPM: {cca2: 'PM', Country: 'Saint Pierre and Miquelon'},
  VCT: {cca2: 'VC', Country: 'Saint Vincent and the Grenadines'},
  WSM: {cca2: 'WS', Country: 'Samoa'},
  SMR: {cca2: 'SM', Country: 'San Marino'},
  STP: {cca2: 'ST', Country: 'Sao Tome and Principe'},
  SAU: {cca2: 'SA', Country: 'Saudi Arabia'},
  SEN: {cca2: 'SN', Country: 'Senegal'},
  SRB: {cca2: 'RS', Country: 'Serbia'},
  SYC: {cca2: 'SC', Country: 'Seychelles'},
  SLE: {cca2: 'SL', Country: 'Sierra Leone'},
  SGP: {cca2: 'SG', Country: 'Singapore'},
  SVK: {cca2: 'SK', Country: 'Slovakia'},
  SVN: {cca2: 'SI', Country: 'Slovenia'},
  SLB: {cca2: 'SB', Country: 'Solomon Islands'},
  SOM: {cca2: 'SO', Country: 'Somalia'},
  ZAF: {cca2: 'ZA', Country: 'South Africa'},
  SGS: {cca2: 'GS', Country: 'South Georgia and the South Sandwich Islands'},
  SSD: {cca2: 'SS', Country: 'South Sudan'},
  ESP: {cca2: 'ES', Country: 'Spain'},
  LKA: {cca2: 'LK', Country: 'Sri Lanka'},
  SDN: {cca2: 'SD', Country: 'Sudan'},
  SUR: {cca2: 'SR', Country: 'Suriname'},
  SJM: {cca2: 'SJ', Country: 'Svalbard and Jan Mayen'},
  SWZ: {cca2: 'SZ', Country: 'Swaziland'},
  SWE: {cca2: 'SE', Country: 'Sweden'},
  CHE: {cca2: 'CH', Country: 'Switzerland'},
  SYR: {cca2: 'SY', Country: 'Syrian Arab Republic'},
  TWN: {cca2: 'TW', Country: 'Taiwan'},
  TJK: {cca2: 'TJ', Country: 'Tajikistan'},
  TZA: {cca2: 'TZ', Country: 'Tanzania, United Republic of'},
  THA: {cca2: 'TH', Country: 'Thailand'},
  TLS: {cca2: 'TL', Country: 'Timor-Leste'},
  TGO: {cca2: 'TG', Country: 'Togo'},
  TKL: {cca2: 'TK', Country: 'Tokelau'},
  TON: {cca2: 'TO', Country: 'Tonga'},
  TTO: {cca2: 'TT', Country: 'Trinidad and Tobago'},
  TUN: {cca2: 'TN', Country: 'Tunisia'},
  TUR: {cca2: 'TR', Country: 'Turkey'},
  TKM: {cca2: 'TM', Country: 'Turkmenistan'},
  TCA: {cca2: 'TC', Country: 'Turks and Caicos Islands'},
  TUV: {cca2: 'TV', Country: 'Tuvalu'},
  UGA: {cca2: 'UG', Country: 'Uganda'},
  UKR: {cca2: 'UA', Country: 'Ukraine'},
  ARE: {cca2: 'AE', Country: 'United Arab Emirates'},
  GBR: {cca2: 'GB', Country: 'United Kingdom'},
  USA: {cca2: 'US', Country: 'United States'},
  UMI: {cca2: 'UM', Country: 'United States Minor Outlying Islands'},
  URY: {cca2: 'UY', Country: 'Uruguay'},
  UZB: {cca2: 'UZ', Country: 'Uzbekistan'},
  VUT: {cca2: 'VU', Country: 'Vanuatu'},
  VEN: {cca2: 'VE', Country: 'Venezuela'},
  VNM: {cca2: 'VN', Country: 'Vietnam'},
  VGB: {cca2: 'VG', Country: 'Virgin Islands, British'},
  VIR: {cca2: 'VI', Country: 'Virgin Islands, U.S.'},
  WLF: {cca2: 'WF', Country: 'Wallis and Futuna'},
  ESH: {cca2: 'EH', Country: 'Western Sahara'},
  YEM: {cca2: 'YE', Country: 'Yemen'},
  ZMB: {cca2: 'ZM', Country: 'Zambia'},
  ZWE: {cca2: 'ZW', Country: 'Zimbabwe'},
};
